language: r
cache: packages

os: 
  - osx
  - linux

before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev
  # Rmpfr
  - sudo apt install -qq libmpfr-dev


r_github_packages:
  - Giappo/mbd
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/beastier@develop
  - ropensci/mauricer
  - ropensci/babette
  - richelbilderbeek/mcbette
  - richelbilderbeek/nLTT
  - rsetienne/PBD/PBD
  - richelbilderbeek/becosys
 
before_script:
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e "mauricer::install_beast2_pkg(\"NS\")"
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - sudo pip install proselint


after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'library(goodpractice); gp()'
