language: r
cache: packages

os: 
 # - osx
  - linux

r_github_packages:
  - Giappo/mbd
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/beautier
  - ropensci/beastier
  - ropensci/mauricer
  - richelbilderbeek/mcbette
  - thijsjanzen/nLTT
  - rsetienne/PBD/PBD
  - richelbilderbeek/becosys

before_install:
    # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install imagemagick; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
  # Java
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install r-cran-rjava; fi  
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi

before_script:
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e "beastier::is_beast2_installed()"
  - Rscript -e 'mauricer::install_beast2_pkg("NS")'
  - Rscript -e 'mauricer::is_beast2_ns_pkg_installed()'
  - beast2_installed_before=$(Rscript -e "beastier::is_beast2_installed()")
  - beast2_ns_pkg_installed_before=$(Rscript -e 'mauricer::is_beast2_ns_pkg_installed()')
  - echo $beast2_installed_before
  - echo $beast2_ns_pkg_installed_before


script:
  - travis_wait 60 R CMD build .
  - travis_wait 60 R CMD check *tar.gz

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'library(goodpractice); gp()'
