language: r
cache: packages

os: 
  - osx
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libmagick++-dev; fi
  
before_script:
  - # if Linux, show distro
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat /proc/version; fi
  - # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi
  - # BEAST2
  - Rscript -e "beastier::install_beast2()"


r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/beastier@develop
  - ropensci/mauricer
  - ropensci/babette
  - richelbilderbeek/mcbette
  - richelbilderbeek/nLTT
  - richelbilderbeek/peregrine

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'library(goodpractice); gp()'
